### ISSUE TITLE
[FEATURE] Add transaction callback

### ISSUE THREAD

**Issue by 4lve** [dialectlabs/blinks#3] opened 2024-07-03 11:02 UTC
I believe there should be a way for a blink to inform the user after the transaction has went through, my proposed idea is to add an optional parameter to `ActionGetResponse` with something like `successHref?: string`, this would make it backwards compatible as you have to specify wether you want this feature.

After the transaction was succsesfull is should make a post request to successHref if there is any with the body
```json
"account": "...",
"signature": "..."
```

Which should in turn return an `ActionGetResponse` without links/buttons.

**Comment by abishekk92** [comment] 2024-07-07 05:23
A callback like this would also be useful for verifying signed messages as well.

**Comment by nickfrosty** [comment] 2024-07-17 15:37
@4lve what do you mean by "inform the user"? the blink already updates the ui with the provided success `message` after the transaction is confirmed

conversation about some sort of callback mechanism is already being discusses on the forum in this sRFC:
https://forum.solana.com/t/srfc-28-blinks-chaining/1734/9

Since this will require a spec change, it should be discussed there :)

**Comment by fsher** [comment] 2024-10-15 18:42
Closing, since chaining solves this issue

**Closed by fsher** 2024-10-15 18:42 UTC
